### ISSUE TITLE
Backlinks plugin duplication

### ISSUE THREAD

**Issue by DawMatt** [joplin/plugins#1]
After installing v1.6.6 (on both Mac and Windows) I tried to install the Backlinks plugin using the new plugin repository.

As you can see from below there is no way to distinguish between the 2 copies of the Backlinks plugin in the repository:

![image](https://user-images.githubusercontent.com/476705/104167539-9a6ec680-5450-11eb-8e92-8f2fc2f7243e.png)

Could we please:

1. Clean up the duplicate plugin
2. Provide some extra information (version number? last update date?) in the UI that would help the user to determine which of the duplicate plugin versions to install?

Ideally we'd do both of these. Item 1 helps with the immediate issue but item 2 gives the user a way to work around the issue if another plugin gets duplicated in future.

**Comment by JackGruber** [comment]
The Backlink Plugin is published by the developer with different IDs (`ambrt.backlinksToNote´, ´joplin.plugin.ambrt.backlinksToNote´) , i think this is the problem.

**Comment by laurent22** [comment]
Yes I think that would need to be fixed by the developer. @ambrt, I would suggest removing the outdated package.

**Comment by ambrt** [comment]
> Yes I think that would need to be fixed by the developer. @ambrt, I would suggest removing the outdated package.

Removed all except for newest.

**Comment by laurent22** [comment]
Thanks for the update @ambrt. I've also updated the plugin repo script so that deleted packages are not displayed in the Joplin app.
