### ISSUE TITLE
Add plugin to repo

### ISSUE THREAD

**Issue by forcewake** [joplin/plugins#5]
Hi.
I have a question about adding plugin to the repository as I've created a plugin for Joplin which generates tags for selected note. There is a small demo:
![demo](https://user-images.githubusercontent.com/1325702/105642063-6657c480-5e98-11eb-8eb8-131f3cfa0482.gif)

Link to plugin's repo - https://github.com/forcewake/joplin-tags-generator
Lins to the latest (and first) release - https://github.com/forcewake/joplin-tags-generator/releases/tag/1.0.0

Should I create some PR or leave as is?

Thank you.

**Comment by Daeraxa** [comment]
These kinds of questions are best asked in the official discourse forum in the development > plugins category - https://discourse.joplinapp.org/c/development/plugins/19
This post has some info on how plugin publishing is handled - https://discourse.joplinapp.org/t/official-joplin-plugin-repository-is-now-ready-if-you-are-developing-a-plugin-please-read-on/13635
The repo is updated automatically by checking published NPM packages starting with "joplin-plugin-..." as I understand it so no PR is necessary to have the plugin added to the repo.

**Comment by forcewake** [comment]
Thank you!
